### ISSUE TITLE
demo3_6.ipynb forloop

### ISSUE THREAD

**Issue by skaae** [avehtari/BDA_py_demos#3]
The forloop code in 3_6 seems to be wrong?

Vectorized likelihood
<img width="483" alt="vectorized" src="https://cloud.githubusercontent.com/assets/2623134/13379980/2aff692a-de36-11e5-86e8-fa1d0d846ce9.png">

forloop likelihood
<img width="419" alt="loop" src="https://cloud.githubusercontent.com/assets/2623134/13379989/629c8aca-de36-11e5-855f-1fee500fc793.png">

The code would be easier to read with `ilogit` renamed to `inverse_logit`

**Comment by tsivula** [comment]
Thanks for pointing out the typo in the comments. Now fixed and commited. The `ilogit_abx_ij**(n - y)` should have been `(1 - inverse_logit_abx_ij)**(n - y)`, just as in the code above. Also changed the variable to `inverse_logit`as suggested.
